### ISSUE TITLE
Set the default branch of repositories to "develop"

### ISSUE THREAD

**Issue by SimonCropp** [Particular/PBot#13]
Since this is where we want PRs to be targeted buy default. It is also the code we want to browse by default

**Comment by andreasohlund** [comment]
Also modify the convert to pull command to target the default/develop
branch if not specified

**Comment by SimonCropp** [comment]
@andreasohlund how is that done?

**Comment by andreasohlund** [comment]
If not specified in the command we should get and use the default branch of
the repo using:

https://developer.github.com/v3/repos/#get

**Comment by SimonCropp** [comment]
on reflection we should not need to automate this. we simply dont create new repos often enough
