### ISSUE TITLE
Pbot is too eager for Slack

### ISSUE THREAD

**Issue by janovesk** [Particular/PBot#16]
Slack does rate limiting on their api. https://api.slack.com/docs/rate-limits Quick summary: one message per second. If you go above this the connection is closed.

We basically ignore this and send too many replies on several of our commands. Depending on how slow the machine hosting the bot is and how time consuming the actual command handling is, this "usually" works. Until it doesn't.

Add to this we also use the slack API to log errors in the #bot_log channel. Things turn really ugly once an error occurs, because that triggers logging which tries to send a new message that trigggers a new error that triggers a new send etc etc. BOOM - pbot dies. (This has been happening regularly, but nobody notices because the windows service hosting pbot gets automatically restarted)

**Comment by janovesk** [comment]
One suggestion is implement a rate limiter that makes sure we don't call Slack more than once per second.

An alternative suggestion is to go through our commands and make sure that we send ONE big reply instead of several smaller.

Or make sure Legion handles this and wait it out.

**Comment by distantcam** [comment]
> We allow bursts over that limit for short periods. However, if your app continues to exceed the limit over a longer period of time it will be rate limited.

So short bursts are allowed, so long as they are small. The restart isn't the bot, it's the comms channel. When the comms dies there's a retry mechanism that opens a new connection.

Yes we should put in a delay of some sort, or a burst limiter.

Messages sent to logging don't report their failure. So you don't end up with a loop of error -> try to log -> error -> try to log -> ...

**Comment by janovesk** [comment]
It is true that they allow burst for short periods of time, but it's very low and we hit the burst limit quite easily. If I run pbot on my machine a simple "list caretakers" is enough for Slack to drop the connection. It works on the slow machine pbot is currently is running on, but that is just luck. If several people ask pbot at the same time, this will blow up.

And once Slack kills the connection the Websocket raises the Error event that SlackAdapter listens to. SlackAdapter then does Logger.ErrorFormat("Slack Socket Error - {0}", errorEventArgs.Exception, errorEventArgs.Exception.Message).

This WILL try to send to #bog_log, but this fails because the connection was just droppped and reconnect fails because Slack has just rate limited you. It's not giving you a new connection straight away. So the send to #bog_log fails, raising another error from the WebSocket. Which tries to log, which fails, which tries to log.

So you get a recursive Socket.Error->SlackAdapter.SocketOnError->Logger.ErrorFormat->Socket.Error that eventually blows up with a StackOverflow that kills the bot. And in the mean time we're pissing of Slack by hammering the API. (This is stuff you could get banned for)

Not sure what you mean by logging messages don't report their failure. Any Logger.Error* will try to send to #bog_log.

My suggestion is to stop logging to Slack and implement a rate limiter in the SlackAdapter.

**Comment by distantcam** [comment]
Ah, so that's why sometimes the list caretakers call was failing.

If they're not giving us a new connection straight away then how is the send causing an error? If the socket is down the send doesn't do anything.

I could have sworn there's some code to stop log loops like the one you described, but I can't find it right now.

Logging is handled by the mmbot projects, so that would require talking to the guy that maintains that. In any case a rate limiter should be implemented.

**Comment by janovesk** [comment]
Implemented in https://github.com/Particular/mmbot/pull/2 and pull sent to mmbot upstream.
