### ISSUE TITLE
Check if PBot has access to repository when adding new repositories

### ISSUE THREAD

**Issue by janovesk** [Particular/PBot#20]
Improvement of an existing command `pbot add repo <name of repo>` to check if pbot has access to the repo. In case it doesn't, prevent pbot from adding this repo until pbot can access it. Present a warning message with appropriate instructions.

**Comment by SeanFeldman** [comment]
When running tests, the credentials we use always yield the following resultsfor Security on any repository (including those that have no PBot added): Admin: True, Push: True, Pull: True

@janovesk I might be missing something, but how would I know that pbot can't operate on a given repo when it lists it and based on credential knows its an admin?
