### ISSUE TITLE
Handle move issue from repositories with names Slack link formates

### ISSUE THREAD

**Issue by janovesk** [Particular/PBot#25]
If you try to move an issue from a repository that has name that Slack link formats(because it looks like a URL, like docs.particular.net), move blows up.

The command ```move issue docs.particular.net#578 to tasks``` is parsed with a reg exp of ```move issue (.*)#(.*) to (.*)$```. The result is an array with the following parameters parsed.
```
[0]	"pbot move issue <http://docs.particular.net#578|docs.particular.net#578> to tasks"
[1]	"<http://docs.particular.net#578|docs.particular.net"
[2]	"578>"
[3]	"tasks"
```` 
The regexp is clearly not working for this scenario.

Expected output is

```
[0]	"pbot move issue <http://docs.particular.net#578|docs.particular.net#578> to tasks"
[1]	"docs.particular.net"
[2]	"578"
[3]	"tasks"
````

**Comment by janovesk** [comment]
Same thing with CopyIssue.

**Comment by andreasohlund** [comment]
I thought I had fixed it for all commands:

https://github.com/Particular/PBot/blob/master/src/PBot/BotCommand.cs#L44

But obviously not, can you take a look @janovesk ?

**Comment by andreasohlund** [comment]
Also in addition to the syntax `{repo}#{issueno}` should we support the full url as well?

Easier when you copy paste

**Comment by janovesk** [comment]
I saw that, @andreasohlund. Doesn't work in this case because the regexp selects ```<http://docs.particular.net#578|docs.particular.net``` (missing ">") and ```578>```(extra ">") instead of ```<http://docs.particular.net#578|docs.particular.net>``` and ```578```, making the fix miss the pattern it is looking for.

**Comment by janovesk** [comment]
Agree on the full url support, I'd say copy paste is use case 1.

**Comment by andreasohlund** [comment]
Cool, can you take a stab at fixing it?

**Comment by janovesk** [comment]
Will do!
