### ISSUE TITLE
Limit the amount of notifications by only getting notifications that are marked with certain labels

### ISSUE THREAD

**Issue by ramonsmits** [Particular/PBot#31]
When you subscribe to a repository you can all notifications. This can act a bit like a firehose. It would be nice you could instruct pbot to notify you when a issue has a certain label.

**Comment by andreasohlund** [comment]
How does this align with the github teams?

If we did a better job with the teams would we need this?

Ie people ping relevant teams as needed?

**Comment by ramonsmits** [comment]
Yes, that would probably work. A team would then maybe represent a guild, role or taskforce. What I want to solve is that I need to be subscribed to all repositories and receive all notificaties of which a lot are interesting but not all are important to act on it. Especially when you have not opened your mailbox for a few days.

Maybe my workflow is not the correct one but I browse to all notifications in my mailbox and scan them for importance and delete them if I think I do not have to act on them.

**Comment by andreasohlund** [comment]
This is the current guidance:

https://github.com/Particular/Housekeeping/wiki/What-repos-should-I-be-subscribed-to

Can you see if it still makes sense?

Would it help?

**Comment by andreasohlund** [comment]
@ramonsmits I propose that we close this one since github teams + unsubscribing to all repos you're not caretaking/intetrested in should do the trick?

**Comment by ramonsmits** [comment]
@andreasohlund  I'm still thinking about a more structured solution to get updated instead of the notification model. Going to close this one.
