### ISSUE TITLE
Keep labels when moving issues between repositories

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/PBot#32]
Taskforce: @adamralph @SeanFeldman 

When an issue is moved, labels are not preserved and lost.

**Comment by SeanFeldman** [comment]
@Particular/pbot should pbot by default move labels as well or should it be optional? 
I find it inconvenient to use PBot to move items, but then going one by one to fix labels.

**Comment by adamralph** [comment]
The required labels should be created if they don't exist. Any extraneous labels in the repo containing the new issue can be cleaned up using the pbot label sync and mapping.
