### ISSUE TITLE
Convert to pull doesn't work with repo names with dots

### ISSUE THREAD

**Issue by andreasohlund** [Particular/PBot#46]
`convert docs.particular.net#752 to pull from cleanup-uow to master`

gives

`Issue number should be a valid number dude!`

I have a hunch this is due to the repo beeing names like a url `docs.particular.net` since we've had that issue for other commands.

Also we should consider the full url to the issue to make it easier to just copy and paste, eg:

`convert https://github.com/Particular/docs.particular.net/issues/752 to pull from cleanup-uow to master`

**Comment by adamralph** [comment]
IMHO the convert to pull feature is counterproductive and should be removed.

@Particular/pbot-maintainers thoughts?
