### ISSUE TITLE
"Pbot move issue" completed task, but failed at moving all comments

### ISSUE THREAD

**Issue by sergioc** [Particular/PBot#50]
Ran ​`pbot move issue https://github.com/Particular/Collaboration/issues/121 to platformdevelopment`​ and it moved the issue to https://github.com/Particular/PlatformDevelopment/issues/444 but not all comments were moved along.

*Note: I've moved the remaining comments manually by myself in the meanwhile.*

**Comment by andreasohlund** [comment]
This is by design,  @SimonCropp removed the moving of comments to avoid all the spam it creates. Moving and issue is a good time clean it up by summarizing the comments  in the description (the comments are still available on the original issue if needed)

**Comment by sergioc** [comment]
I changed the help output for this command to clarify the command's behavior - see https://github.com/Particular/PBot/blob/242a33b9b6aced125325156c6429fc6e0fb100d7/src/PBot/Issues/MoveIssue.cs from https://github.com/Particular/PBot/pull/51
