### ISSUE TITLE
Web API available?

### ISSUE THREAD

**Issue by hmemcpy** [Particular/PBot#52]
Is there an API to invoke PBot commands from HTTP?

**Comment by andreasohlund** [comment]
What's the use case?

**Comment by adamralph** [comment]
This raises a question I've been asking for a while. Should the automations that pbot encapsulates be moved to a service, and pbot reduced to an integration point (UI) only?

**Comment by andreasohlund** [comment]
:+1: pretty sure this is similar to where @SzymonPobiega wants to move the automation stuff he's built

**Comment by adamralph** [comment]
No movement for >6 months here so closing. The point I raise is a discussion which may appear again as we evolve pbot.
