### ISSUE TITLE
Syncomatic update duplicates files when case does not match

### ISSUE THREAD

**Issue by timbussmann** [Particular/PBot#56]
when doing a syncomatic update to a repo already having a nuget.config file with upper-case letters (NuGet.Config) pbot adds a new nuget.config file instead of replacing the existing one which causes lots of fun on windows machines.

does pbot have it's own git configuration? Could it use the core.ignoreCase setting?

**Comment by adamralph** [comment]
Should this be moved to https://github.com/Particular/SyncOMatic ?
