### ISSUE TITLE
pbot not applying label "withdrawn: moved" when moving issues in /collaboration

### ISSUE THREAD

**Issue by sergioc** [Particular/PBot#72]
pbot not applying label "withdrawn: moved" when moving issues in /collaboration. Not sure if the problem is also occurring with other repos.

**Comment by andreasohlund** [comment]
Occurs in all repos

**Comment by sergioc** [comment]
Not a bug since this [wasn't yet implemented](https://github.com/Particular/Collaboration/issues/260) in the first place.

**Comment by andreasohlund** [comment]
@sergioc since we seem to need this will you raise an issue to get it done?

**Comment by sergioc** [comment]
@andreasohlund the issue already exists and is still open: https://github.com/Particular/Collaboration/issues/260

**Comment by andreasohlund** [comment]
Move it to this repo?

**Comment by sergioc** [comment]
Moved to https://github.com/Particular/pbot/issues/74
