### ISSUE TITLE
Pig me does not work for me

### ISSUE THREAD

**Issue by mauroservienti** [Particular/PBot#76]
If I issue a `pig me` command to pbot I get the following exception:

```
System.AggregateException: One or more errors occurred. ---> Octokit.ApiValidationException: Validation Failed
  at Octokit.Connection.HandleErrors(IResponse response) in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 563
  at Octokit.Connection.<RunRequest>d__51.MoveNext() in C:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:line 545
```

**Comment by adamralph** [comment]
@mauroservienti does it work if you type:

`pbot pig mauroservienti`

?

**Comment by adamralph** [comment]
Hmmm.. the answer is probably no, because that doesn't work for me either :worried:

**Comment by adamralph** [comment]
Will probably need debugging...

**Comment by mauroservienti** [comment]
@adamralph confirmed. No, it doesn't work.

> Will probably need debugging...

I'm sorry :smile:

**Comment by adamralph** [comment]
Assigning to myself so I remember to pick it up, but I'm not sure when that will be. If anyone else wants to pick it up in the meantime, please feel free.

**Comment by adamralph** [comment]
@mauroservienti is it the same problem as this? https://github.com/Particular/PBot/issues/71

**Comment by mauroservienti** [comment]
@adamralph if I ask `PBot` for `list credentials` I get this response:

```
Credentials for mauro.servienti
mauro.servienti: mauroservienti
```

Is this what I should see?

**Comment by mauroservienti** [comment]
So...I issued once more: `register credential github-username=mauroservienti` and now it works. Closing this one.
