### ISSUE TITLE
Identify user that moved an issue with pbot

### ISSUE THREAD

**Issue by sergioc** [Particular/PBot#77]
Currently there's no way to see who executed `pbot move` commands. This makes it hard to audit who made the move and discuss any conflicts, especially if the user who issued the command did not participate in the original issue. 

In addition to adding the name of who executed the command, it would also be useful for pbot to automatically CC the user who moved the issue on the original issue, so that if there's still discussion happening in the original issue, that user will be made aware of it.

Example issue that covers the 2 use cases above: https://github.com/Particular/Collaboration/issues/260

**Proposed format:**
- In closed issue, change pbot comment to `Moved to REPO/#ISSUE_NO by @USER`
- in new issue, change pbot comment to `Issue moved by @USER. Originally opened in ORIGINAL_REPO#ISSUE_NO`

CC // @adamralph

**Comment by adamralph** [comment]
I like the idea.

For the messages, how about:

* Moved to `repoA/#xxx` by `@johndoe`
* Moved from `repoB/#yyy` by `@johndoe`

**Comment by sergioc** [comment]
>- Moved to repoA/#xxx by @johndoe
- Moved from repoB/#yyy by @johndoe

@adamralph :+1:

**Comment by adamralph** [comment]
Impact M since currently there is *no way* to tell who moved an issue!
