### ISSUE TITLE
Copy all comments into a single comments when moving an issue

### ISSUE THREAD

**Issue by adamralph** [Particular/PBot#83]
The copying of all comments when moving an issue [was reduced](https://github.com/Particular/PBot/commit/237fa0f22f878ddbcc01fd5f2e3d5a6a1a9f22ba) to only the first comment (often referred to as the "description") and the next comment after that.

This continues to surprise people and it makes it awkward to track the history of the issue.

IIRC this was done to reduce the number of email notifications.

I propose that we restore the copying of all comments, but we copy all of them into a single comment on the new issue, in an appropriate format.

**Comment by hmemcpy** [comment]
This is also what ZenHub's "Move issue" is doing - copying all comments into a single top level comment. All the info is retained, but without notification overload.

**Comment by adamralph** [comment]
Marking as impact M since there are continuous requests for this.

**Comment by adamralph** [comment]
We need to bear in mind the ramifications of moving an issue from a private repo to a public repo. Perhaps in that case, we should insist on a mandatory parameter which controls whether or not to copy all the comments. It may also be wise to include the initial comment (often referred to as the "description") in that setting.

**Comment by mauroservienti** [comment]
Should we also expose a command setting to allow the user to change this behavior? We faced this in the Collaboration Squad sync today and said that it was nice to have something like `pbot move .... .... -full` or `pbot move .... .... -compact` or `pbot move .... .... -cc:<comments-count>`.

**Comment by adamralph** [comment]
@mauroservienti that probably makes sense. What would `-compact` do?

**Comment by mauroservienti** [comment]
As I started thinking to this I was expecting the `pbot move` to have a default behavior, if the default behavior is to copy the whole comments history then `-compact` can revert the behavior to what it is now; otherwise if the default behavior is what it is now then the `-full` option may be needed. It is one or the other, not both.

**Comment by adamralph** [comment]
I was thinking that by default, all comments should be copied.

In the special case of moving an issue from a private repo to a public one, pbot would refuse to move the issue unless an extra argument is supplied and give a message like:

> You are moving an issue from a private repo to a public repo. Private comments may not be suitable for public consumption. You must indicate how many comments to move into the new issue by supplying either a number or `all` at the end of the command, e.g. `pbot move issue source-repo#123 to destination-repo 0` or `pbot move issue source-repo#123 to destination-repo all`.

**Comment by mauroservienti** [comment]
amazing :smile: :+1:
