### ISSUE TITLE
Search string returned by pbot pig me is incorrect

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/PBot#84]
The search string that is supposed to show all issues where the user is mentioned returns an incorrect URL.

When I ran `pbot pig me` this morning the last URL returned was https://github.com/issues?q=is%3Aopen+mentions%3A2+user%3AParticular where it should have been https://github.com/issues?q=is%3Aopen+user%3AParticular+mentions%3AWilliamBZA

**Comment by adamralph** [comment]
I think this should be `Tag: Maintainer Prio` but... there is no maintainer group! :open_mouth:

**Comment by adamralph** [comment]
There is now! @Particular/pbot-maintainers

**Comment by adamralph** [comment]
@WilliamBZA thanks for raising this. Finally fixed in 0.1.172, which is now released.
