### ISSUE TITLE
Remove pbot pig

### ISSUE THREAD

**Issue by adamralph** [Particular/PBot#98]
Now that GitHub supports multiple assignees, we can use that instead of listing the task force in the issue body.

This would make pbot pig redundant in it's current form, since GitHub can be used instead, e.g.
- https://github.com/issues/assigned
- https://github.com/pulls

There are ideas to [expand pbot pig outside the scope of GitHub](https://github.com/Particular/PBot/issues/82), but I'm not sure how feasible they are. Unless we decide to do this, there is no reason to keep pbot pig in place.

**Comment by adamralph** [comment]
[RFC](https://particularsoftware.slack.com/archives/announcements/p1469785479000025).

**Comment by agastypula** [comment]
I think two links mentioned by you @adamralph are well enough check what we are assigned to. 

pbot pig me wasn't working for me anyway ;)

**Comment by adamralph** [comment]
@agastypula thanks for chiming in.

Out of interest, does this work for you?

`pbot pig agastypula`

**Comment by agastypula** [comment]
I'm surprised, it works :) thanks for checking @adamralph

**Comment by adamralph** [comment]
@agastypula you're welcome.

In case you're interested, this reason for this is that when pbot sees "me", it tries to use *your username* to query GitHub. In the context of Slack, all that pbot knows is your Slack username, which is "aga". You have to tell pbot that your *GitHub* username is "agastypula" with this command:

`pbot register credential github-username=agastypula`

After that, `pbot pig me` should work.

(If everyone had the same username in both Slack and GitHub, none of this would be required :wink:.)

**Comment by karenfruchtman** [comment]
Does this imply that we need to always assign all task force members as assignees on issues?  If so, I'm not a fan.  I think the role of the facilitator needs to be highlighted so we easily know who is responsible for moving an issue to completion.  If there are multiple assignees, we will need to add this to the issue templates and open the issue to know who the facilitator is. For both Collaboration and Staff Success, that is not idea.  

Do we need to be consistent across areas of strategy here?

**Comment by adamralph** [comment]
There are two approaches:

1. We assign all task force members to the issue, and note the facilitator in the description
2. We assign the facilitator to the issue, and not the task force members in the description

I favour option 1 for the following reasons:

* The more useful and common search is "which task forces am I on" rather than "which issues am I the facilitator for"? We should favour the the built in GitHub facility for listing issues for the more common search https://github.com/issues/assigned and use a custom search (pbot or otherwise) for the less common search.
* Many task forced issues do not have a facilitator
* I am already seeing more task forces listed by assignment to issues than by listing within the description
* The UI favours listing multiple people by picking them from the dropdown, rather than typing them out, which feeds into the point above.

If people still feel it is useful to list which issues they are facilitating, we can replace the current `pbot pig me` with something like `pbot facilitator me`.

**Comment by adamralph** [comment]
> Do we need to be consistent across areas of strategy here?

I think that would be better.

**Comment by karenfruchtman** [comment]
@adamralph I guess I prefer to reserve judgment until the issue about reviewing the role of the facilitator is done.  But, your arguments for number 1 above are compelling.

**Comment by adamralph** [comment]
For reference: "Clarify the role of facilitator" https://github.com/Particular/Collaboration/issues/464
